dist: xenial
language: node_js
node_js:
  - "10"
before_install:
  npm install -g firebase-tools
jobs:
  include:
    - stage: Deploy desktop vault website to Firebase
      script: |
        cd ./ui/vault-web
        npm install
        npm test
        npm run build
        firebase deploy --only hosting:acumany-vault --token "$FIREBASE_TOKEN"