dist: xenial
language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: install dependencies
      script: |
        cd ./client/vault-web
        npm install
        npm test
        npm run build