matrix:
  allow_failures:
    env: ALLOW_TASK_FAILURE=yes
  include:
    - stage: Deploy desktop Vault website to Firebase
      language: node_js
      dist: xenial
      env: ALLOW_TASK_FAILURE=yes
      node_js:
        - "10"
      before_install:
        - npm install -g firebase-tools
      script: |
        cd ./ui/vault_desktop_web
        npm install
        npm test
        npm run build
        firebase deploy --only hosting:acumany-vault --token "$FIREBASE_TOKEN"
    - stage: Build Android Vault App
      language: android
      jdk: oraclejdk8
      env: ALLOW_TASK_FAILURE=yes
      sudo: true
      android:
        components:
          - android-28
          - build-tools-28.0.3
          - extra
          - tools
          - platform-tools
          - extra-google-m2repository
          - extra-android-m2repository
        licenses:
          - android-sdk-preview-license-.+
          - android-sdk-license-.+
          - google-gdk-license-.+
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - lib32stdc++6
            - libc6:i386
            - libncurses5:i386
            - libstdc++6:i386
            - lib32z1
            - libbz2-1.0:i386
      before_install:
        - ls $ANDROID_HOME/tools/bin
        - yes | sudo $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-28"
        - yes | sudo $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3"
        - yes | sudo $ANDROID_HOME/tools/bin/sdkmanager --update
        - yes | sudo $ANDROID_HOME/tools/bin/sdkmanager --licenses
        - git clone https://github.com/flutter/flutter.git -b beta
        - ./flutter/bin/flutter doctor -v
      script: |
        echo "Not implemented"
    - stage: Build iOS Vault App
      language: objective-c
      env: ALLOW_TASK_FAILURE=yes
      before_install:
        - git clone https://github.com/flutter/flutter.git -b beta
        - ./flutter/bin/flutter doctor -v
      script: |
        echo "Not implemented"
