dist: xenial
language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: install dependencies
      script: cd ./client/acumany-vault-web && npm install
    - stage: unit test
      script: npm test
    - stage: production build
      script: npm run build