dist: xenial
language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: install dependencies
      script: |
        cd ./ui/vault-web
        npm install
        npm test
        npm run build
        firebase deploy --only hosting:acumany-vault --token "$FIREBASE_TOKEN"